steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ancient-coin-classifier/coin-classifier-backend', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ancient-coin-classifier/coin-classifier-backend']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'coin-classifier-backend',
         '--image', 'gcr.io/ancient-coin-classifier/coin-classifier-backend',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--allow-unauthenticated']
